### ISSUE TITLE
MakeHuman startup error - 1.3.0 alpha

### ISSUE THREAD

**Issue by richardmv** [makehumancommunity/makehuman#244]
Platform: ArchLinux 6.9.2-arch1-1 EndeavourOS
Python Version: 3.12.3
Numpy Version: 1.26.4

Error occurred on startup: wl_subsurface@43: error 0: no parent
The Wayland connection experienced a fatal error: protocol error

also:
could not load 9_export_ogre
ModuleNotFoundError: No module named 'imp'

I haven't been able to start it up since the update; I'm hoping I didn't just do something foolish on my end to break things. Might be a Python error, since the error is showing up in terminal but not in the log file.

[makehuman-debug.txt](https://github.com/makehumancommunity/makehuman/files/15491989/makehuman-debug.txt)
[makehuman.log](https://github.com/makehumancommunity/makehuman/files/15491991/makehuman.log)

![CrashLog 5-29-24](https://github.com/makehumancommunity/makehuman/assets/20386452/8a75341f-6a28-4337-8182-87d65b7a6030)

**Comment by richardmv** [comment]
I've noticed I have no Python 3.11 install. The change from Python 3.11's imp module to 3.12's 'importlib' may be causing at least the more minor of the two issues. I'm installing the older build and will test with that.

**Comment by black-punkduck** [comment]
This happens with ancient parts in our software ...

please change the line 

**import imp**

to

**import importlib as imp**

with a text editor in `plugins/9_export_ogre/__init__.py`  (line 41)

If that does the job I will fix it. On my box it works, but I also have the old "imp" module.

But that is not wayland, that is simply the deprecated old "imp" module which was replaced by importlib (which is used by makehuman also).

**Comment by black-punkduck** [comment]
hhrrmpf ... okay ... it is already fixed, so Aranuvir was faster than me  ;)

**Comment by richardmv** [comment]
Made the change on my end and that does fix the issue with 9_export_ogre but doesn't fix the Wayland issue, so I'm still unable to launch MakeHuman. It's likely a Wayland issue and not a MH issue. I should be able to reboot my computer without Wayland and see if that lets me open it.

**Comment by black-punkduck** [comment]
yupp but I guess that is identical now to #233
